version: "3.8"

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: players_clubs_management
    networks:
      players-doc-api-swagger-service:
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=11111111 --execute 'show databases;' || exit 1"]
      interval: 15s
      retries: 5

  players-doc-api-swagger:
    container_name: players-doc-api-swagger
    depends_on:
      - mysql
    image: vladbogdadocker/players-doc-api-swagger:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/players_clubs_management
    ports:
      - "8084:8084" #browser:local
    networks:
      players-doc-api-swagger-service:
    restart: on-failure

networks:
  players-doc-api-swagger-service:

