spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chinook
    username: root
    password: 11111111
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    hiddenmethod:
      filter:
        enabled: true